export const GET_PATIENT_REQUEST ="GET_PATIENT_REQUEST";
export const GET_PATIENT_SUCCESS ="GET_PATIENT_SUCCESS";
export const GET_PATIENT_FAILURE ="GET_PATIENT_FAILURE";




export const GET_PRESCRIPTION_REQUEST ="GET_PRESCRIPTION_REQUEST";
export const GET_PRESCRIPTION_SUCCESS ="GET_PRESCRIPTION_SUCCESS";
export const GET_PRESCRIPTION_FAILURE ="GET_PRESCRIPTION_FAILURE";


export const GET_PATIENT_BY_NAME_REQUEST ="GET_PATIENT_BY_NAME_REQUEST";
export const GET_PATIENT_BY_NAME_SUCCESS ="GET_PATIENT_BY_NAME_SUCCESS";
export const GET_PATIENT_BY_NAME_FAILURE ="GET_PATIENT_BY_NAME_FAILURE";